<?php

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Link;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_system_breadcrumb_alter().
 */
function tederic_breadcrumb_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
    $active_theme = \Drupal::theme()->getActiveTheme()->getName();
    if (!empty($node->getType()) && $active_theme == 'tederic') {
      $links = $breadcrumb->getLinks();

      $lbt = $node->getTitle();
      switch ($node->getType()) {
        case 'solution':
        case 'solution_part':
          $links[0] = Link::createFromRoute(t('Solutions'), '<nolink>');
          break;
        case 'product':
          // Remove first breadcrumb for Product.
          unset($links[0]);
          // Sub Category term name as last breadcrumb title.
          $sub_category_tid = $node->get('field_series_sub_category')->getValue()[0]['target_id'];
          $term = Term::load($sub_category_tid);
          $lbt = $term->getName();
          break;
        case 'page':
        case 'worldwide':
          $links[0] = Link::createFromRoute(t('Company'), '<nolink>');
          break;
      }

      $links[] = Link::createFromRoute($lbt, '<nolink>');

      $breadcrumb = new Breadcrumb();
      $breadcrumb->setLinks($links);
    }
  }
}
