<?php

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Link;

/**
 * Implements hook_system_breadcrumb_alter().
 */
function tederic_breadcrumb_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
    $links = $breadcrumb->getLinks();

    switch ($node->getType()) {
      case 'solution':
      case 'solution_part':
        $links[0] = Link::createFromRoute(t('Solutions'), '<nolink>');
        break;
      case 'product':
        $links[0] = Link::createFromRoute(t('Products'), '<front>');
        break;
      case 'worldwide':
        $links[0] = Link::createFromRoute(t('Company'), '<nolink>');
        break;
    }

    $breadcrumb = new Breadcrumb();
    $breadcrumb->setLinks($links);

    $breadcrumb->addLink(Link::createFromRoute($node->getTitle(), '<nolink>'));
  }
}
