<?php

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Link;

/**
 * Implements hook_system_breadcrumb_alter().
 */
function tederic_breadcrumb_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
    $active_theme = \Drupal::theme()->getActiveTheme()->getName();
    if (!empty($node->getType()) && $active_theme == 'tederic') {
      $links = $breadcrumb->getLinks();

      switch ($node->getType()) {
        case 'solution':
        case 'solution_part':
          $links[0] = Link::createFromRoute(t('Solutions'), '<nolink>');
          break;
        case 'product':
          // $sub_category = $node->get('field_series_sub_category');
          unset($links[0]);
          break;
        case 'page':
        case 'worldwide':
          $links[0] = Link::createFromRoute(t('Company'), '<nolink>');
          break;
      }

      $links[] = Link::createFromRoute($node->getTitle(), '<nolink>');

      $breadcrumb = new Breadcrumb();
      $breadcrumb->setLinks($links);
    }
  }
}
