<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function tederic_common_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'search_block_form') {
    $form['keys']['#attributes']['placeholder'] = t('Search across the tederic for products, technology or solutions');
    $form['keys']['#suffix'] = '<div class="close-search"></div>';
  }

  // Exposed form.
  if ($form_id == 'views_exposed_form') {
    // Check view id.
    $view_ids = ['products'];
    $view = $form_state->getStorage('view');
    if (in_array($view['view']->id(), $view_ids)) {
      // Check view display.
      $display = $view['display']['id'];
      if ($display == 'products_block') {
        // Add Series library.
        $form['#attached']['library'][] = 'tederic/series';
        // Change All option label.
        $form['series_sub_category']['#options']['All'] = t('All');
      }
    }
  }
}

/**
 * Implements hook_preprocess_links().
 */
function tederic_common_preprocess_links(&$variables) {
  $variables['language_id'] = \Drupal::languageManager()->getCurrentLanguage()->getId();
}
