<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function tederic_common_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'search_block_form') {
    $form['keys']['#attributes']['placeholder'] = t('Search across the tederic for products, technology or solutions');
    $form['keys']['#suffix'] = '<div class="close-search"></div>';
  }

  if ($form_id == 'menu_link_content_social-media-menu_form') {
    // to do...
  }
}

/**
 * Implements hook_preprocess_links().
 */
function tederic_common_preprocess_links(&$variables) {
  $variables['language_id'] = \Drupal::languageManager()->getCurrentLanguage()->getId();
}
